updated Workflow

diff --git a/.github/workflows/infra-ci-cd.yml b/.github/workflows/infra-ci-cd.yml
--- a/.github/workflows/infra-ci-cd.yml
+++ b/.github/workflows/infra-ci-cd.yml
@@ -4,13 +4,11 @@ on:
     branches: [ main ]
   pull_request:
 
-#Special permissions required for OIDC authentication
 permissions:
   id-token: write
   contents: read
   pull-requests: write
 
-#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
 env:
   ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
   ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
@@ -20,164 +18,81 @@ env:
 defaults:
   run:
     working-directory: ./infra/tf-app  
-  
+
 jobs:
-  tflint:
+  terraform-plan:
+    name: 'Terraform Plan'
     runs-on: ubuntu-latest
+    env:
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
-    - uses: actions/checkout@v4
-      name: Checkout source code
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - uses: actions/cache@v4
-      name: Cache plugin dir
-      with:
-        path: ~/.tflint.d/plugins
-        key: tflint-${{ hashFiles('.tflint.hcl') }}
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_wrapper: false
 
-    - uses: terraform-linters/setup-tflint@v4
-      name: Setup TFLint
-      with:
-        tflint_version: latest
+      - name: Terraform Init
+        run: terraform init
 
-    - name: Show version
-      run: tflint --version
+      - name: Terraform Format
+        run: terraform fmt -check
 
-    - name: Init TFLint
-      run: tflint --init
-      env:
-        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
-        GITHUB_TOKEN: ${{ github.token }}
-
-    - name: Run TFLint
-      id: tflint
-      run: tflint -f compact
-
-  terraform-plan:
-        name: 'Terraform Plan'
-        runs-on: ubuntu-latest
-        env:
-          #this is needed since we are running terraform with read-only permissions
-          ARM_SKIP_PROVIDER_REGISTRATION: true
-        outputs:
-          tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
-    
-        steps:
-        # Checkout the repository to the GitHub Actions runner
-        - name: Checkout
-          uses: actions/checkout@v4
-    
-        # Install the latest version of the Terraform CLI
-        - name: Setup Terraform
-          uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_wrapper: false
-    
-        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-        - name: Terraform Init
-          run: terraform init
-    
-        # Checks that all Terraform configuration files adhere to a canonical format
-        # Will fail the build if not
-        - name: Terraform Format
-          run: terraform fmt -check
-    
-        # Generates an execution plan for Terraform
-        # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-        - name: Terraform Plan
-          id: tf-plan
-          run: |
-            export exitcode=0
-            terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-    
-            echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-            
-            if [ $exitcode -eq 1 ]; then
-              echo Terraform Plan Failed!
-              exit 1
-            else 
-              exit 0
-            fi
-            
-        # Debugging step: Ensure tfplan exists
-        - name: List files before uploading artifact
-          run: ls -la
-
-        # Save plan to artifacts  
-        - name: Publish Terraform Plan
-          uses: actions/upload-artifact@v4
-          with:
-            name: tfplan
-            path: tfplan
-            retention-days: 7  # Keep the artifact for 7 days
-            
-        # Create string output of Terraform Plan
-        - name: Create String Output
-          id: tf-plan-string
-          run: |
-            TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-            
-            delimiter="$(openssl rand -hex 8)"
-            echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-            echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-            echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-            echo "" >> $GITHUB_OUTPUT
-            echo '```terraform' >> $GITHUB_OUTPUT
-            echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-            echo '```' >> $GITHUB_OUTPUT
-            echo "</details>" >> $GITHUB_OUTPUT
-            echo "${delimiter}" >> $GITHUB_OUTPUT
-            
-        # Publish Terraform Plan as task summary
-        - name: Publish Terraform Plan to Task Summary
-          env:
-            SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-          run: |
-            echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
           
-        # If this is a PR post the changes
-        - name: Push Terraform Output to PR
-          if: github.ref != 'refs/heads/main'
-          uses: actions/github-script@v7
-          env:
-            SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-          with:
-              github-token: ${{ secrets.GITHUB_TOKEN }}
-              script: |
-                const body = `${process.env.SUMMARY}`;
-                github.rest.issues.createComment({
-                    issue_number: context.issue.number,
-                    owner: context.repo.owner,
-                    repo: context.repo.repo,
-                    body: body
-                })
-  # This will only run if the terraform plan has changes, and when the PR is approved and merged to main.
+          if [ $exitcode -eq 1 ]; then
+            echo "Terraform Plan Failed!"
+            exit 1
+          else 
+            exit 0
+          fi
+
+      # Debugging step: Ensure tfplan exists
+      - name: List files before uploading artifact
+        run: ls -la
+
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfplan
+          path: ./infra/tf-app/tfplan
+          retention-days: 7  
+
   terraform-apply:
     name: 'Terraform Apply'
     if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
     runs-on: ubuntu-latest
     environment: production
     needs: [terraform-plan]
-    
+
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+      - name: Terraform Init
+        run: terraform init
 
-    # Download saved plan from artifacts  
-    - name: Download Terraform Plan
-      uses: actions/download-artifact@v4
-      with:
-        name: tfplan
+      - name: Download Terraform Plan
+        uses: actions/download-artifact@v4
+        with:
+          name: tfplan
+          path: ./infra/tf-app  # Ensure it downloads to the correct working directory
 
-    # Terraform Apply
-    - name: Terraform Apply
-      run: terraform apply -auto-approve tfplan
+      - name: List files after downloading tfplan
+        run: ls -la ./infra/tf-app  # Debugging step
+
+      - name: Terraform Apply
+        run: terraform apply -auto-approve ./infra/tf-app/tfplan
